backend:
  name: github
  repo: nadavspi/nadav.is
  branch: v3.0.0

media_folder: static/assets
public_folder: assets

collections:
  - name: Books
    label: Book
    folder: books
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: publication, label: Year of publication, widget: string }
      - { name: rating, label: Rating, widget: string }
      - { name: link, label: Link, widget: string, required: false }
      - { name: cover, label: Cover, widget: image, required: false }
      - name: highlights
        label: Highlights
        widget: list
        required: false
        fields:
          - { name: highlight, label: Highlight, widget: text }
      - { name: body, label: Body, widget: markdown, required: false }
