backend:
  name: github
  repo: nadavspi/nadav.is

media_folder: static/assets
public_folder: assets

collections:
  - name: Books
    label: Book
    folder: books
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
